### ISSUE TITLE
Keyboard scrolling doesn't work

### ISSUE THREAD

**Issue by GreenReaper** [QMatrixClient/Quaternion#453] opened 2018-12-02 00:36 UTC
### Description

I can't scroll with the keyboard, only with the scroll thumb.

### Steps to reproduce

- Open a room which has more than a page of chat messages.
- Click on the chat area and press PgUp.
- Observe that the chat does not scroll up to show more chat messages.

On the right there is a blue scroll line with a very small (one line high) rectangular scroll thumb in front of the middle of the line. the middle. I can drag that thumb to scroll the message list, but it immediately snaps back to the middle once I release it. The lower portion of the blue line disappears once I scroll to the top, but the line above the thumb never disappears even once at the top.

I expected to be able to just press PgUp and PgDown with the window selected (with or without the text area selected), but these keys do not appear to do anything. PgDown does not work either, if I am scrolled up via the mouse.

### Version information

I'm using Quaternion v0.0.9.3 on Windows 10 version 1809, installed by extracting the GitHub release ZIP file into Program Files (x86), git commit 32697ffedb1a2968582bc21ec2dfe4dcdebaedfa.

---

Having just filled in a title, I realize this *might* be a duplicate of #448. If that fixes it, a release with it in would be nice, as it's a killer bug on this platform; I can't really evaluate the software properly as it is. My netbook doesn't come with a touchscreen, and hitting the scrollbar with a TrackPoint is fiddly as well. ^_^

**Comment by KitsuneRal** [comment] 2019-01-10 07:16
It's actually a duplicate of #123.

**Closed by KitsuneRal** 2019-01-10 07:16 UTC
Labels: duplicate
