### ISSUE TITLE
Chat room body doesn't appear after upgrade to 0.0.9

### ISSUE THREAD

**Issue by 26000** [QMatrixClient/Quaternion#356] opened 2018-05-08 17:27 UTC
### Description

I compiled quaternion-0.0.9-1 from AUR on Arch, and when I click on a room name, nothing happens. I see a solid background-color rectangle. The console output is something like this:
```
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
194 µs to  select room #matrix:matrix.org
94 µs to  select room #matrix:matrix.org
8 µs to  select room #matrix:matrix.org
Read marker is on-screen, at (0|"$1525798155860241biZLT:matrix.org")
Read marker is off-screen
Bottommost shown message index was 0
ImageProvider::requestImage: "mxc://kotobank.ch/JnHsnkOjVlEFyDGDeLJpmjrE"
Read marker is on-screen, at (0|"$1525798155860241biZLT:matrix.org")
ImageProvider::requestImage: "mxc://kotobank.ch/JnHsnkOjVlEFyDGDeLJpmjrE"
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
```

I thought it's related to #355, but mine doesn't work with any color scheme, white or dark. `hello.cpp` example works.

### Steps to reproduce

 1. Compile `qauternion-0.0.9-1` from AUR
 2. Launch it
 3. Click on any room title

### Version information
- **Quaternion version**: 0.0.9
- **Qt version**: `qt5-base 5.10.1-8 (qt qt5)`
- **Install method**: AUR
- **Platform**: Arch Linux, bspwm (quaternion works neither with nor without compositor), both `qt5-quickcontrols` and `qt5-quickcontrols2` are installed

**Comment by KitsuneRal** [comment] 2018-05-19 09:52
Thanks for the report (and sorry for taking time to respond), I'll look into this in the nearest days.

**Comment by KitsuneRal** [comment] 2018-05-24 12:13
@26000, please try to build the above commit; I'm interested in output lines with `onShownChanged`.

**Comment by 26000** [comment] 2018-05-24 20:39
I couldn't build, says the following after running `cmake ..`:
```
CMake Error at CMakeLists.txt:43 (add_subdirectory):
  The source directory

    /home/user/bin/Quaternion/lib

  does not contain a CMakeLists.txt file.


-- 
-- =============================================================================
--                           Quaternion Build Information
-- =============================================================================
-- Build type: Debug
-- Using compiler: GNU 8.1.0
-- Using Qt 5.10.1 at /
-- Quaternion install prefix: /usr/local
-- =============================================================================
-- 
-- Configuring incomplete, errors occurred!
See also "/home/user/bin/Quaternion/CMakeFiles/CMakeOutput.log".
```

I didn't add prefix paths, but it should build anyway?

**Comment by KitsuneRal** [comment] 2018-05-25 00:20
You seem to have not checked out the library in `lib/`. In your Quaternion directory, do `git submodule init && git submodule update`, as described in Quaternion's `BUILDING.md`.

**Comment by 26000** [comment] 2018-05-25 10:03
Oh, i'm sorry for being stupid :/ Prints this to stderr:
```
qt5ct: using qt5ct plugin
Debug:  false
qml: QML view loaded
qml: Base colours: #eff0f1 on #232629
qt5ct: D-Bus global menu: no
qt5ct: D-Bus system tray: no
--- Show time!
QXcbConnection: XCB error: 5 (BadAtom), sequence: 858, resource id: 0, major code: 19 (DeleteProperty), minor code: 0
QPainter::begin: Paint device returned engine == 0, type: 3
QImage::scaled: Image is a null image
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
qml: Chat: getPreviousContent disabled
Connected to room "!cURbafjkfsMDVwdRDQ:matrix.org" as "@<user>:matrix.org"
qml: onShownChanged($15272424631159fKFwx:vurpo.fi,true): y=0, view.contentY=-584, view.height=584
qml: onShownChanged($15272424631159fKFwx:vurpo.fi,false): y=0, view.contentY=-584, view.height=584
ImageProvider::requestImage: "mxc://vurpo.fi/rAVYYdwTozdZslBFduliksPR"
qml: onShownChanged($15272424631159fKFwx:vurpo.fi,true): y=-65, view.contentY=-584, view.height=584
qml: Chat: getPreviousContent enabled
Sorting 15465 user(s) in "Matrix HQ" took 706 ms
15465 user(s) in the room
760 ms to  select room #matrix:matrix.org
QPainter::begin: Paint device returned engine == 0, type: 3
QImage::scaled: Image is a null image
qml: onShownChanged($1527242467426mzTpJ:maunium.net,true): y=0, view.contentY=-480, view.height=480
qml: onShownChanged($1527242467426mzTpJ:maunium.net,false): y=0, view.contentY=-480, view.height=480
ImageProvider::requestImage: "mxc://maunium.net/jdlSfvudiMSmcRrleeiYjjFO"
qml: onShownChanged($1527242467426mzTpJ:maunium.net,true): y=-68, view.contentY=-480, view.height=480
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
QImage::scaled: Image is a null image
QPainter::begin: Paint device returned engine == 0, type: 3
QImage::scaled: Image is a null image
QPainter::begin: Paint device returned engine == 0, type: 3
QPainter::begin: Paint device returned engine == 0, type: 3
```

I've removed lots of `QPainter::begin: Paint device returned engine == 0, type: 3`.

**Comment by KitsuneRal** [comment] 2018-05-29 08:30
Sorry for taking time to respond. Thanks, judging by this output, QML works just fine (and its geometry looks proper); my next guess is that there's a problem with z-order of the QML container unpredictably failing. I'll investigate more on what can be done with this.

**Comment by KitsuneRal** [comment] 2018-06-11 07:13
Sorry for making you wait. I think I have found another way to setup a QML widget, let's see if it works in your case. I'll let you know about the specific commit later today after testing.

**Comment by KitsuneRal** [comment] 2018-06-16 07:09
Please try the latest master, passing `-DUSE_QQUICKWIDGET` to CMake. Should fix your issues with QML visibility but I have questions to its stability so please try to use it heavily (if it works, of course) and see if it crashes on you. If it does, I'll try to look for another fix.

**Comment by KitsuneRal** [comment] 2018-06-23 06:13
Assuming that the cause of the problem is unpredictable stacking order of the QML view, this is a duplicate of #355 - further tracking will occur there.

**Closed by KitsuneRal** 2018-06-23 06:13 UTC
Labels: bug, duplicate

**Comment by dessalines** [comment] 2019-02-09 01:05
I'm still getting this issue with a dark theme.

qt5ct: using qt5ct plugin
quaternion 0.0.9.4-git

**Comment by KitsuneRal** [comment] 2019-02-11 03:08
@dessalines, what is your Qt version?
