### ISSUE TITLE
flatpak: Qt plugin "flatpak" missing

### ISSUE THREAD

**Issue by tidux** [QMatrixClient/Quaternion#349] opened 2018-04-17 20:13 UTC
```
$  flatpak run com.github.quaternion
This application failed to start because it could not find or load the Qt platform plugin "flatpak"
in "".

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Reinstalling the application may fix this problem.
$
```

This issue appears on both Arch Linux and Debian 9, both of which are fully up to date, which removes distro packaging as a source of the bug.

**Comment by KitsuneRal** [comment] 2018-04-20 01:25
@elvisangelaccio, do you have an idea what is wrong here?

**Comment by KitsuneRal** [comment] 2018-04-22 08:44
I'm afraid I'm not quite qualified to solve this. Apparently Flatpak changed their ways and now there should be `QT_QPA_FLATPAK_PLATFORM` set to the actually used platform (xcb or wayland). I don't want to enforce it in the flatpak JSON file; I suppose there should be some better way?

**Comment by KitsuneRal** [comment] 2018-04-22 08:45
For the record, this is what landed in KDE: https://phabricator.kde.org/D8223

**Comment by KitsuneRal** [comment] 2018-04-22 08:55
@nedrichards, can you please clarify what's the right way to deal with QPA plugins in Flatpak these days?

**Comment by elvisangelaccio** [comment] 2018-04-22 14:57
I cannot reproduce on Arch Linux, the application starts just fine for me. Make sure you don't have a `QT_QPA_PLATFORM=flatpak` environment variable set somewhere, because the `flatpak` QPA plugin is gone.

@KitsuneRal `QT_QPA_FLATPAK_PLATFORM` is an internal env variable set by KWin, it has nothing to do with upstream flatpak.

**Comment by nedrichards** [comment] 2018-04-22 19:25
Yeah - the user needs to make sure they have the latest verson of the KDE SDK - that handles all that itself now.

**Comment by tidux** [comment] 2018-04-22 19:26
The bug was encountered on Debian 9.4.

**Comment by KitsuneRal** [comment] 2018-04-23 01:46
@elvisangelaccio @nedrichards Thanks! While we are at it - should I still have the flatpak JSON file with upstream code? My understanding is that the file from https://github.com/flathub/com.github.quaternion is used to build Flatpaks; and the one in https://github.com/QMatrixClient/Quaternion is out of date - should I just drop it?

**Comment by nedrichards** [comment] 2018-04-23 14:27
The one in flathub is the one that's used to build flatpaks on flathub, correct. As for if you should have a JSON file upstream, that's kind of up to you - you might want to have different development builds with different settings (a bit like the way gnome does them) and handing someone a flatpak bundle to test is easier for normal people and reproducible so you know the bug is gone on both systems.

But yeah, if you don't use it, you can absolutely drop it.

**Comment by elvisangelaccio** [comment] 2018-04-24 21:04
@tidux Please post the output of `flatpak --user info org.kde.Platform`

**Comment by tidux** [comment] 2018-05-01 20:09
```
$ flatpak --user info org.kde.Platform//5.9
runtime/org.kde.Platform/x86_64/5.9 flathub ae1b1bf29599d41d5c5ad4be214cd41817a7cb49aca99add0f307dda50fc76e4
```

**Comment by elvisangelaccio** [comment] 2018-05-03 20:38
@tidux Don't you have the date in the output?

This is what I get:

```
$ flatpak --user info org.kde.Platform//5.9
Ref: runtime/org.kde.Platform/x86_64/5.9
ID: org.kde.Platform
Arch: x86_64
Branch: 5.9
Origin: flathub
Collection ID: 
Date: 2018-04-28 01:34:31 +0000
Subject: Move gnome integration plugins back to runtime repo (59a6af13)
Commit: 2e7ca179765ba9b725ea2e8cf673d725493f8aa18f80ad10100ca7cc9f0c8c0e
Parent: 9d56f71175fc47a4b71e7cadf4cba7c58f4c1be31036505d77b204a1b2368cf1
Location: /home/elvis/.local/share/flatpak/runtime/org.kde.Platform/x86_64/5.9/2e7ca179765ba9b725ea2e8cf673d725493f8aa18f80ad10100ca7cc9f0c8c0e
Installed size: 1,1 GB
```

**Comment by tidux** [comment] 2018-05-03 20:39
No.  This is on Debian 9.4.

On May 3, 2018 1:38:43 PM PDT, Elvis Angelaccio <notifications@github.com> wrote:
>@tidux Don't you have the date in the output?
>
>This is what I get:
>
>```
>$ flatpak --user info org.kde.Platform//5.9
>Ref: runtime/org.kde.Platform/x86_64/5.9
>ID: org.kde.Platform
>Arch: x86_64
>Branch: 5.9
>Origin: flathub
>Collection ID: 
>Date: 2018-04-28 01:34:31 +0000
>Subject: Move gnome integration plugins back to runtime repo (59a6af13)
>Commit:
>2e7ca179765ba9b725ea2e8cf673d725493f8aa18f80ad10100ca7cc9f0c8c0e
>Parent:
>9d56f71175fc47a4b71e7cadf4cba7c58f4c1be31036505d77b204a1b2368cf1
>Location:
>/home/elvis/.local/share/flatpak/runtime/org.kde.Platform/x86_64/5.9/2e7ca179765ba9b725ea2e8cf673d725493f8aa18f80ad10100ca7cc9f0c8c0e
>Installed size: 1,1 GB
>```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/QMatrixClient/Quaternion/issues/349#issuecomment-386429036

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by elvisangelaccio** [comment] 2018-05-03 21:26
Your version of flatpak?

**Comment by tidux** [comment] 2018-05-08 01:12
```
$ flatpak --version
Flatpak 0.8.9
```

**Comment by rushsteve1** [comment] 2018-06-18 03:29
Bit late to the party but a few things on this changed today:
Both the internal Flatpak manifest and the Flathub one have been redone by me.

Additionally the version listed by tidux on May 7, ie version `0.8.9` is considered to be very out of date and was back then too. Considering the rate of development of Flatpak it is very likely there was a breaking change.

Seeing as how everything has now changed and the issue was only experienced by one person on an outdated Flatpak version, I think this issue should be closed. Especially since it is marked as part of the v0.1 milestone.

**Comment by KitsuneRal** [comment] 2018-06-18 03:59
Agree. @tidux, feel free to reopen this if you experience the problem on the most recent Quaternion flatpak (which has just turned 0.0.9.2 as I'm writing this).

**Closed by KitsuneRal** 2018-06-18 03:59 UTC
Labels: building/packaging
